on: [push]

job:
  hello_world_job:
    run-on: ubuntu-lastest
    name: A job to say hello
    steps:
      - name: Hello word action step
        id: hello
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time'
        run: echo "The time was ${{ step.hello.outputs.time }}"
        